# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Theology of Code'
tagline:          'Nonemoticoner&rsquo;s blog'
description:      'Nonemoticoner&rsquo;s blog about Computer Science related technologies.'
url:              http://nonemoticoner.github.io
baseurl:          /blog

author:
  name:           'Nonemoticoner'
  url:            https://github.com/Nonemoticoenr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Nonemoticoner/blog
